
version: 2

models:
    - name: events_user_level
      description: "Flattens the events table to user level"
      columns:
          - name: user_id
            description: "The unique identifier of the user that RSVPed for this event"
            tests:
                - unique
                - not_null
          - name: name
            description: "The title of the event"
            tests:
                - not_null
          - name: status
            description: "The status of the event"
            tests:
                - not_null
          - name: venue_id
            description: "Unique identifier of the venue where this event takes place"
            tests:
                - not_null
          - name: time
            description: "The timestamp of when the event will start (or has started)"
            tests:
                - not_null
          - name: created
            description: "Timestamp of the moment the event was created by the organiser"
            tests:
                - not_null
          - name: duration_hours
            description: "The duration of the event, in hours"
            tests:
                - not_null
          - name: rsvp_limit
            description: "The maximum number of YES RSVPs that this event will allow"
            tests:
                - not_null
          - name: response
            description: "User's RSVP, yes, no or waitlist"
            tests:
                - not_null
          - name: user_when
            description: "Timestamp of the moment the user gave their RSVP"
            tests:
                - not_null
          - name: days_to_rsvp
            description: "How many days the user took to RVSP after the event's creation date"
            tests:
                - not_null
          - name: guests
            description: "If permitted, the number of guests that the user is planning to bring to the event"
            tests:
                - not_null
                
    - name: users
      description: "Flattens the users table"
      columns:
          - name: user_id
            description: "A unique identifier for this user"
            tests:
                - unique
                - not_null
          - name: country
            description: "Country where the user resides"
            tests:
                - not_null
          - name: city
            description: "City where the user resides"
            tests:
                - not_null
          - name: group_id
            description: "The unique identifier of the group that the user has joined"
            tests:
                - not_null
          - name: joined_date
            description: "Date of when the user joined the group"
            tests:
                - not_null
 
    - name: venues
      description: "Selects relevant columns from venues table"
      columns:
          - name: venue_id
            description: "A unique identifier for the venue"
            tests:
                - unique
                - not_null
          - name: name
            description: "Name of the venue"
            tests:
                - not_null
          - name: country
            description: "Country of the venue"
            tests:
                - not_null
          - name: city
            description: "City of the venue"
            tests:
                - not_null

    - name: joined_events_user_venue_info
      description: "joins the events, user and venues information"
      columns:
          - name: user_id
            description: "A unique identifier for this user"
            tests:
                - not_null
          - name: user_city
            description: "City where the user resides"
            tests:
                - not_null
          - name: user_country
            description: "Country where the user resides"
            tests:
                - not_null
          - name: event_name
            description: "The title of the event"
            tests:
                - not_null
          - name: user_response
            description: "User's RSVP, yes, no or waitlist"
            tests:
                - not_null
          - name: event_status
            description: "The status of the event"
            tests:
                - not_null
          - name: event_created_date
            description: "Timestamp of the moment the event was created by the organiser"
            tests:
                - not_null
          - name: group_id
            description: "The unique identifier of the group that organized the event"
            tests:
                - not_null
          - name: rsvp_limit
            description: "The maximum number of YES RSVPs that this event will allow"
            tests:
                - not_null
          - name: days_to_rsvp
            description: "How many days the user took to RVSP after the event's creation date"
            tests:
                - not_null
          - name: venue_id
            description: "A unique identifier for the venue"
            tests:
                - not_null
          - name: venue_name
            description: "Venue's name"
            tests:
                - not_null
          - name: venue_city
            description: "Venue's city"
            tests:
                - not_null
          - name: venue_country
            description: "Venue's country"
            tests:
                - not_null
          - name: same_country
            description: "Boolean that checks if user's country is the same as venue's country"
            tests:
                - not_null
